In [2]:
import pandas as pd
import numpy as np

In [10]:
def w_avg(df, values, weights):
    d = df[values]
    w = df[weights]
    return (d * w).sum() / w.sum()

In [11]:
#create DataFrame
df = pd.DataFrame({'sales_rep': ['A', 'A', 'A', 'B', 'B', 'B'],
                   'price': [8, 5, 6, 7, 12, 14],
                   'amount': [1, 3, 2, 2, 5, 4]})

In [12]:
df

sales_rep  price  amount
0         A      8       1
1         A      5       3
2         A      6       2
3         B      7       2
4         B     12       5
5         B     14       4

In [13]:
#find weighted average of price
w_avg(df, 'price', 'amount')

9.705882352941176

## GROUPING AND USING FUNCTION

In [16]:
#find weighted average of price, grouped by sales rep
df.groupby('sales_rep').apply(w_avg, 'price', 'amount')

sales_rep
A     5.833333
B    11.818182
dtype: float64

## USING NUMPY

In [19]:
#weigthed average

In [17]:
df.groupby("sales_rep").apply(lambda x: np.average(x['price'], weights=x['amount']))

sales_rep
A     5.833333
B    11.818182
dtype: float64

In [ ]:
#numpy.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>, *, where=<no value>)
#Compute the arithmetic mean along the specified axis.

In [18]:
df.groupby("sales_rep").apply(lambda x: np.mean(x['price']))

sales_rep
A     6.333333
B    11.000000
dtype: float64

In [22]:
a = np.zeros((2, 2*2), dtype=np.float32)
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

In [24]:
a[0,:]=1
a[1,:]=0.1
a

array([[1. , 1. , 1. , 1. ],
       [0.1, 0.1, 0.1, 0.1]], dtype=float32)

In [26]:
a = np.array([[1, 2], [3, 4]])
np.mean(a)

2.5

In [27]:
np.mean(a,axis=0)

array([2., 3.])

In [28]:
np.mean(a,axis=1)

array([1.5, 3.5])